import type { Metadata } from "next";
import "./globals.scss";
import { brownLight } from "./fonts";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/auth.context";

export const metadata: Metadata = {
  title: "form nextjs task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${brownLight.className} bg-primary-50`}>
        <AuthProvider>{children}</AuthProvider>
        {/* toast */}
        <ToastContainer />
      </body>
    </html>
  );
}
